version: '3'
services:

  postgres:
    image: postgres:16.1
  #  hostname: localhost
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    network_mode: "host"
    volumes:
      - ./pgdata:/var/lib/postgresql/

  py_air_quality:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    network_mode: "host"
    depends_on:
      - postgres
